%% Input parameters
E0 = 1; %Amplitude of transmitted signal

mu0 = 4*pi*1e-7; %Vacuum permeability
mu = [1 1 100] * mu0; %Permeability of medium layers

epsilon0 = 8.8541853e-12; %Vacuum permittivity
epsilon = [1 6 1e3] * epsilon0; %Permittivity of medium layers

sigma = [1e-9 5e-3 7e6]; %Conductivity of medium layers

omega = 2*pi*19e9; %Frequency of EM wave generated by the system
d = [5 15] * 1e-2; %Layers' thichness (m)

SNR = 5; %Signal to noise ratio

fs = 5e11; %Sampling frequency (Hz)
obs_time = 2e-8; %Observation time (s)
t = 0:1/fs:(obs_time - 1/fs);

%% Derived parameters
gamma = ones(size(mu)); %Propagation constant of medium
eta = ones(size(mu)); %Intrinsic impedance of medium
vp = ones(size(mu)); %EM Wave velocity in medium

for k = 1:length(mu)
    gamma(k) = sqrt(1i*omega*mu(k)*(sigma(k)+1i*omega*epsilon(k)));
    eta(k) = sqrt(1i*omega*mu(k)/(sigma(k)+1i*omega*epsilon(k)));
    vp(k) = 1/sqrt(mu(k)*epsilon(k)/2*(sqrt(1+(sigma(k)/(omega*epsilon(k)))^2)+1));
end

R_coef_fw = ones(size(d)); %Reflection coefficient from k-th layer to (k+1)-th layer
R_coef_bw = ones(size(d)); %Reflection coefficient from (k+1)-th layer to k-th layer
T_coef_fw = ones(size(d)); %Transmission coefficient from k-th layer to (k+1)-th layer
T_coef_bw = ones(size(d)); %Transmission coefficient from (k+1)-th layer to k-th layer

z = 0;
for k = 1:length(d)
    z = z + d(k);
    R_coef_fw(k) = exp(-2*gamma(k)*z)*((eta(k+1)-eta(k))/(eta(k+1)+eta(k)));
    R_coef_bw(k) = exp(2*gamma(k+1)*z)*((eta(k)-eta(k+1))/(eta(k+1)+eta(k)));
    T_coef_fw(k) = exp((gamma(k+1)-gamma(k))*z)*2*eta(k+1)/(eta(k+1)+eta(k));
    T_coef_bw(k) = exp((gamma(k+1)-gamma(k))*z)*2*eta(k)/(eta(k+1)+eta(k));
end

%% Pulse
Pr = zeros(1,1+(length(d)-1)*4);
tr = zeros(size(Pr));

Pr(1) = E0*R_coef_fw(1)*exp(1i*(0-2*d(1)/vp(1))*omega);
tr(1) = 2*d(1)/vp(1);

tz = 0;
T_coef = 1;
index = 2;
for k = 2:length(d)
    tz = tz + 2*d(k-1)/vp(k-1);
    T_coef = T_coef*T_coef_fw(k-1)*T_coef_bw(k-1);
    for q = 1:4
        Pr(index) = E0*(R_coef_fw(k)^q)*(R_coef_bw(k-1)^(q-1))*T_coef*exp(1i*omega*(0-2*q*d(k)/vp(k)-tz));
        tr(index) = 2*q*d(k)/vp(k)+tz;
        index = index + 1;
    end
end

bar(tr, real(Pr), 'BarWidth', 0.4);
xlabel('time (s)');
ylabel('Amplitude (V/m)');

%% Sinusoidal wave
Er = E0*R_coef_fw(1)*exp(1i*(t-2*d(1)/vp(1))*omega);
Er(t<2*d(1)/vp(1)) = 0;

tz = 0;
T_coef = 1;
for k = 2:length(d)
    tz = tz + 2*d(k-1)/vp(k-1);
    T_coef = T_coef*T_coef_fw(k-1)*T_coef_bw(k-1);
    for q = 1:4 %Assume there is four multiple reflections inside layer 2
        temp = E0*(R_coef_fw(k)^q)*(R_coef_bw(k-1)^(q-1))*T_coef*exp(1i*omega*(t-2*q*d(k)/vp(k)-tz));
        temp(t<(2*q*d(k)/vp(k)+tz)) = 0;
        Er = Er + temp;
    end
end

clear temp;

Er = real(Er);

figure;
plot(t, Er);
xlabel('time (s)');
ylabel('Amplitude (V/m)');

%Fourier transform to find the frequency of the reflected signal
ps = abs(fft(Er)/length(t));
frequency = fs*(0:(length(t)/2))/length(t);

figure;
plot(frequency,ps(1:(length(t)/2)+1));
